### ISSUE TITLE
Questions about the output shape

### ISSUE THREAD

**Issue by JiamingSuen** [ClementPinard/Pytorch-Correlation-extension#2]
Hi @ClementPinard , thanks for this great work.
I'm having trouble comparing the output with your implementation against NVIDIA's. I observe that the output shape of your `correlation_sampler` is `torch.Size([16, 3, 3, 100, 100])` while NVIDIA's implementation is `torch.Size([16, 49, 94, 94])`, given input size `torch.Size([16, 64, 100, 100])` and other parameter shown in your benckmark scritps. 
Would you please explain why you choose to output in this shape and how to convert them into NVIDIA's format? I didn't find an obvious conversion.
Thanks for your time.

**Comment by ClementPinard** [comment]
Hello, that's a good question, and I should write something for that, but here are the main differences :

max_displacement in NVIDIA implementation is the max shift you can get, whether it is negative or positive. It would be equivalent to have for a correlation of kernel_size 3 a paremeter of max_displacement to 1. To keep consistent with kernel size notation,I changed it to the actuzal size of patches you correlate.
I also changed how the stride2 worked. I called it `patch_dilation` and made it works just like dilation in convolutions. In short, when you have in NVIDIA these parameters `max_displacement = x, stride2 = y` you would have to do `patch_size = (x - 1)/(2*y), patch_dilation = y`

Now for padding, the output size is no longer dependant to patch_size, it's only a function of kernel_size, pad and stride. You don't have to add padding regarding patch_size and dilation parameters. It made the implementation much clearer actually, but it could change if requested.

the output is now 5D ! since we sample the correlation on 2 dimensions, we should have `patch_sizeH * patch_sizeW` feature maps. It only made sense to keep them as 2 and mlet the user to the collate job if wanted.

```python
b, ph, pw, h, w = output.size()
output_collated = output.view(b, ph * pw, h, w)
```

One last thing, result is not normalized by input channel size anymore, so to get consistent result with NVIDIA you also have to do `output /= input1.size(1)` . You may end up doing this every time, but at least the correlation sampler is doing a pure correlation and nothing else.

**Comment by ClementPinard** [comment]
Also, don't take benchmark into account, Made some mistakes, results were too good to be true :(
I'm gonna update it soon

**Comment by JiamingSuen** [comment]
Thanks for your reply, sad to hear it's not faster than NVIDIA's implementation.
Is there any room for further optimization?

**Comment by ClementPinard** [comment]
I just updated the code, and now it's faster, especially for kernel size of 1 :)
I also updated the documentation on how to use it compared to NVIDIA's code.
cheers :)
