### ISSUE TITLE
About the batch_size and kernel_size

### ISSUE THREAD

**Issue by shankyle** [ClementPinard/Pytorch-Correlation-extension#31]
Hello! Thanks for your valuable work again! I am confused about the batch size and the input1 input2. e.g. `input1 = (16, 3, 224, 224)` and `input2 = (16, 3, 224, 224)`，is the correlation of input1 and input2: cat_{i=0 => 15}{corr(input1[i, 3, 224, 224], input2[i, 3, 224, 224])}? 
And the order of the input1 and input2 is: for a pixel x_{i,j} in input1, compute the patch around the location i, j in the input2. Is that right?
Finally, what is the kernel size meaning? I guess if kernel size = 1, it is: 1 pixel in the input1 => patch in the input2; kernel size=2: 4 pixel in the input1 => patch in the input2. I did not find the detail of flownet-C in Flownet and Flownet2.0 of the kernel size. Thanks for your help!

**Comment by shankyle** [comment]
And I was wondering that if it has normalization of channel dimension.?_?

**Comment by ClementPinard** [comment]
This module does not feature channel normalization, but it could easily be added.

as for your first questions:
1) you assumption is right, the every operation is strictly equivalent of applying it on a single element of the batch and then reconcatenating the output togother (as it is mostly the case for every module ;) ).

2) Yes this operation is asymetrical, be careful ! corr(input1, input2) actually yields the same values, but not in the same order.

3) for FlowNet, kernel size is always of size 1, which makes the correlation module not an actual correlation operation ! If the kernel size is more than one, you will have the local correlation at a particular point of the input1 with its neighbourhood of size `kernel_size`, computed with another point of input2, with its neighbourhood too. This operation is very similar to convolution, but instead of a fixed kernel for the whole image, we take kernels from input2 with a particular shift each time. When kernel_size is 1, this operation becomes only `input1[i1,j1] * input2[i2, j2]`

**Comment by shankyle** [comment]
I see! Thanks for your patient to my questions! I am trying to compute the channel-wise(depth-wise) correlation, which likes the `group` parameters in PyTorch. May you have a plan to add the group operation in your code? I guess it may help many people! Thanks a lot!

**Comment by shankyle** [comment]
Sorry for the above question！It can be easily computed in the batch dimension! Thanks for your reply again!
