### ISSUE TITLE
Feature-wise correlation

### ISSUE THREAD

**Issue by cattaneod** [ClementPinard/Pytorch-Correlation-extension#41]
Hi,
I'm trying to implement feature-wise correlation, required for VCN: Volumetric Correspondence Networks.
The main difference is that feature-wise correlation does not sum over the channel dimension, the output cost volume is therefore (B x C x PatchH x PatchW x oH x oW) instead of (B x PatchH x PatchW x oH x oW).

The forward pass is already implemented here: https://github.com/gengshan-y/Pytorch-Correlation-extension
I'm trying to implement the backward pass, i thought that changing this
```prod_sum[ph_off][pw_off] += gradOutput[n][ph][pw][i2][j2] * val;```
to this
```prod_sum[ph_off][pw_off] += gradOutput[n][c][ph][pw][i2][j2] * val;```
would do the job, but it's not working.

I'm testing it with torch.autograd.gradcheck, and the jacobians from analytical and numerical are different (same values, but in different order).

Do you have any idea on how to implement the backward pass?

**Comment by ClementPinard** [comment]
Very easy workaround : convert the feature map shape from BxCxHxW to (B*C)x1xHxW to simulate a correlation to feature map of only one feature, and then convert back.

Otherwise, you could probably do a simpler parallelism scheme since your function is easier since there isn't any reduction operation.

**Comment by cattaneod** [comment]
Thank you for the workaround idea, I will try that!
