### ISSUE TITLE
Backward computation logic

### ISSUE THREAD

**Issue by gcilli** [ClementPinard/Pytorch-Correlation-extension#47]
Hi Clement, thank you for this repository, it is very helpful.

I am trying to modify it a bit to adapt to my task and I am struggling with the backward implementation. Could you please explain why the indexing logic is so different between the forward and backward pass? 

More specifically, could you answer these questions?

1. why do we use only the `thread` index in the forward pass and two indices, namely `ph_off` and `pw_off` in the backward pass?
2. why `THREADS_FORWARD` is 32 and `THREADS_BACKWARD` is 5?

Thank you!

**Comment by ClementPinard** [comment]
Hi sorry for the late late anwer, hope it will still be relevent to you by this time i answered your question !

For the forward pass, we deal with a 1D register, while for backward we have a 2D register.
So we deal with 32 threads forward, and 25 threads backward

Also, keep in mind that the actual total number of threads is number of block * number of threads. What we call threads in CUDA is a grid of threads that are connected together and can operate on the same memory location efficiently. Think of this as processes vs threads.

In terms of why the two are different is purely pragmatic, we have several options to parallelize :

the un parallelized operation for forward is roughly this : 

```python
rinput1 = input1.transpose(0,2,3,1)  # [B, H, W, C]
rinput2 = input2.transpose(0,2,3,1)  # [B, H, W, C]

for b in range(B):
    for i in range(H):
        for j in range(W):
            for k in range(C):
                # everything above is parallelized, everything below is not
                for l in range(-d, d):
                    for m in range(-d, d):
                        for n in range(K):
                            for o in range(K):
                                output[b, l, m, i, j, k] += rinput1[b, i+n, j+o, k] * rinput2[b, i+l+n, j+m+o, k])
```

You can probably see that in the CUDA code we parallelized over batch size (very obvious), output size (H and W), and lastly channel(C), but not for patch size (k and l) nor for kernel size (m and n). Note that for loops can be swapped, especially channel and kernel size.

You can then see that the C dimension collapses, we make a reduction over this dimension. Reduction operations are hard to parallelize because it implies concurrent writes, but we can manage it with a shared registry which is the size of the threads. In case the Channel size is greater than 32, we do some "strided loop" (see https://developer.nvidia.com/blog/cuda-pro-tip-write-flexible-kernels-grid-stride-loops/)

here is the algorithm for input1

```python

for b in range(B):  # batch is not parallelized ! crazy !
    for i in range(H):
        for j in range(W):
            for k in range(C):
                for l in range(-d, d):
                    for m in range(-d, d):
                        # everything above is parallelized (except batch), everything below is not
                        for n in range(K):
                            for o in range(K):
                                grad_input1[b, k, i, j] += grad_output[b, l, m, i+n, j+o, k] * input2[b, i+l, j+m, k])
```

You can see here the dimension that collapses is no longer channel (in fact it is recreated, the gradient is the same throughout all the channels), but patch sizes. We thus create a shared registry for these two dimension, but this is working essentially the same as with only one dimension. the loops are more complicated than that in actual cuda code because we have to deal with strided correlation (determined by parameters dH and dW)

The question onto why such dimension was parallelized and not the other also resides in trial and error where I tested several ways of viewing this algorithm (you can swap the for loops fairly easily). I initially copied the code from nvidia's implementation, which copied it from FlowNet Caffe implementation, and it turns out that the fastest implementation was the one that was already designed (still need polish though).

The important factors are memory layout (that's why we transpose dimension at the beginning of the forward phase), where threads that are close to each other hould work on data that is close to each other (but not the same location, think of cows eating in row in a farm) this is called memory coalescing (https://developer.nvidia.com/blog/how-access-global-memory-efficiently-cuda-c-kernels/), and Kernel size : you mght end up with compiled code that don't fit in a kernel and thus you need to dumb down your code.

The last factor might have changed now with new hardware, maybe we con change the code a bit to leverage larger kernel stack size.

Hope this was informative to you, fell free to ask question about implementation anytime !

Clément
