### ISSUE TITLE
Tf implementation 

### ISSUE THREAD

**Issue by divamgupta** [ClementPinard/Pytorch-Correlation-extension#5]
HI,

Would you be knowing of any easy to use ( like this one) , correlation layer in tensorflow.

**Comment by ClementPinard** [comment]
Not that I know of, sorry :(
Maybe you can try the [lmbspecialops repo](https://github.com/lmb-freiburg/lmbspecialops), which is from the same lab as the flownet2 team. Namely, they introduced for ECCV a flownet3, which is maybe implemented in tensorflow (they seem to have drifted from caffe to tensorflow lately), so maybe this tensorflow repo of custom operations in tensorflow will be extended.

Otherwise, you can have a look at https://github.com/sampepose/flownet2-tf ,maybe the module they implemented can bu used for something else.

Good luck !

**Comment by divamgupta** [comment]
Thanks!
