### ISSUE TITLE
Do  you have a paper to introduce this project in detail?

### ISSUE THREAD

**Issue by houhouhouhou11** [ClementPinard/Pytorch-Correlation-extension#62]
Do  you have a paper to introduce this project in detail?

**Comment by yellowYuga** [comment]
https://arxiv.org/abs/1512.02134

**Comment by houhouhouhou11** [comment]
@yellowYuga,Thank you very much . Btw, do  you know the differnece of kernal and patch in this project. Where the dilation is unsed in ? kernal or patch? Thank you very much

**Comment by ClementPinard** [comment]
- kernel is the radius of area used for computing correlation. It is very similar to convolution kernel, since it's a weighted sum of the neighbourhood of a particular point, with the difference that here the some is weighted by the corresponding neighbourhood of the second input.

- patch is the different translations we test between input1 and input2. Regular correlation is done with a translation of (0,0), and then we test different translations. for a particular translation u,v, we compute correlIation between `input1[:, u:, v:]` and `input2[:, :-u, :-v]` .

- dilation is the same as dilation in regular convolution, meaning that e.g. for a 3x3 correlation with dilation 2, you actually have 5x5 "a trous" correlation. This is not dependent to different translations tested in patch

- the corresponding dilation paremeter for patch is dilation_patch. Instead of testing every possible integer translation in [-patch_size/2, +patch_size/2] , we multiply every translation tested by dilation_patch. (Meaning we test as many different translation as with a dilation_patch of 1, but the translation are enhanced
